void chanMsg(char *msg,char *channel,int sockfd);
void OUT(int sockfd,char *message);
int Send(int sockfd);
void *Recieve(void *sock);
void PINGING(int sockfd);
void outParse(char *message, int sockfd, char *channel);
void inParse(char *message, int sockfd);
void messParse(char *message, int sockfd);
void parseCommand(char *message,int sockfd, char *channel);
void toLower(char *arr,char *out);
void botCommands(char *user,char *channame,char *msg,int sockfd);
int weather(char *channel, int sockfd, char *location);
void help(char *channel,int sockfd, int pm);
void privM(char *message,char *user,int sockfd);
int randomSpeach(char *msg, int sockfd, char *channel);
void removeLine(char *file,char *file2, int line1, int line2);
int forget(char *user);
int userStats(char *user,char *outmsg);
void Greet(char *user,char *outsrc);
void remember(char *item, char *message);
int remembered(char *item, char *outstr);
void kick(char *channel, int sockfd, char *person);
void JoinChan(char *channel,int sockfd);
void Kick(char *message,int sockfd, char *channel);
void chanVoice(char *channame,char *channel);
void giveMode(char *message, int sockfd, char *channel);
void privMsg(char *message, int sockfd);
void seen(char *person, char *outstr);
void joinScript(char *user, char *channel, int sockfd);
int opList(char *user);
int storeQ(char *msg);
int storeAway(char *msg);
int purgeAway(char *user);
int relayAway(char *channel,int sockfd,char *user);
int checkAway(char *user);
int questionParse(char *user, char *channel, char *array, int sockfd);
void forgetQ(char *array);
void logToFile(char *message, char *user, char *channame);
int searchLogs(char *message,char *usr, char *chn, char *tim, char *msg);
int parseLogs(char *message,char *usr, char *chn, char *tim, char *msg);
void zap_newline (char *str);
void zap_all(char *str);
int clearstr(char *array);
void mainOnjoin(int sockfd);

